# Generated by Django 3.2.7 on 2022-07-12 03:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grayscale', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diary',
            new_name='Grayscale',
        ),
        migrations.AlterModelOptions(
            name='grayscale',
            options={'verbose_name_plural': 'Grayscale'},
        ),
    ]
