# Generated by Django 3.2.7 on 2022-07-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grayscale', '0002_auto_20220712_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='grayscale',
            name='checkbox',
            field=models.BooleanField(default=False, verbose_name='共有'),
        ),
    ]
